const vsttypes = @import("vsttypes.zig");

pub const kCtrlBankSelectMSB: vsttypes.CtrlNumber = 0;
pub const kCtrlModWheel: vsttypes.CtrlNumber = 1;
pub const kCtrlBreath: vsttypes.CtrlNumber = 2;
pub const kCtrlFoot: vsttypes.CtrlNumber = 4;
pub const kCtrlPortaTime: vsttypes.CtrlNumber = 5;
pub const kCtrlDataEntryMSB: vsttypes.CtrlNumber = 6;
pub const kCtrlVolume: vsttypes.CtrlNumber = 7;
pub const kCtrlBalance: vsttypes.CtrlNumber = 8;
pub const kCtrlPan: vsttypes.CtrlNumber = 10;
pub const kCtrlExpression: vsttypes.CtrlNumber = 11;
pub const kCtrlEffect1: vsttypes.CtrlNumber = 12;
pub const kCtrlEffect2: vsttypes.CtrlNumber = 13;
pub const kCtrlGPC1: vsttypes.CtrlNumber = 16;
pub const kCtrlGPC2: vsttypes.CtrlNumber = 17;
pub const kCtrlGPC3: vsttypes.CtrlNumber = 18;
pub const kCtrlGPC4: vsttypes.CtrlNumber = 19;
pub const kCtrlBankSelectLSB: vsttypes.CtrlNumber = 32;
pub const kCtrlDataEntryLSB: vsttypes.CtrlNumber = 38;
pub const kCtrlSustainOnOff: vsttypes.CtrlNumber = 64;
pub const kCtrlPortaOnOff: vsttypes.CtrlNumber = 65;
pub const kCtrlSustenutoOnOff: vsttypes.CtrlNumber = 66;
pub const kCtrlSoftPedalOnOff: vsttypes.CtrlNumber = 67;
pub const kCtrlLegatoFootSwOnOff: vsttypes.CtrlNumber = 68;
pub const kCtrlHold2OnOff: vsttypes.CtrlNumber = 69;
pub const kCtrlSoundVariation: vsttypes.CtrlNumber = 70;
pub const kCtrlFilterCutoff: vsttypes.CtrlNumber = 71;
pub const kCtrlReleaseTime: vsttypes.CtrlNumber = 72;
pub const kCtrlAttackTime: vsttypes.CtrlNumber = 73;
pub const kCtrlFilterResonance: vsttypes.CtrlNumber = 74;
pub const kCtrlDecayTime: vsttypes.CtrlNumber = 75;
pub const kCtrlVibratoRate: vsttypes.CtrlNumber = 76;
pub const kCtrlVibratoDepth: vsttypes.CtrlNumber = 77;
pub const kCtrlVibratoDelay: vsttypes.CtrlNumber = 78;
pub const kCtrlSoundCtrler10: vsttypes.CtrlNumber = 79;
pub const kCtrlGPC5: vsttypes.CtrlNumber = 80;
pub const kCtrlGPC6: vsttypes.CtrlNumber = 81;
pub const kCtrlGPC7: vsttypes.CtrlNumber = 82;
pub const kCtrlGPC8: vsttypes.CtrlNumber = 83;
pub const kCtrlPortaControl: vsttypes.CtrlNumber = 84;
pub const kCtrlEff1Depth: vsttypes.CtrlNumber = 91;
pub const kCtrlEff2Depth: vsttypes.CtrlNumber = 92;
pub const kCtrlEff3Depth: vsttypes.CtrlNumber = 93;
pub const kCtrlEff4Depth: vsttypes.CtrlNumber = 94;
pub const kCtrlEff5Depth: vsttypes.CtrlNumber = 95;
pub const kCtrlDataIncrement: vsttypes.CtrlNumber = 96;
pub const kCtrlDataDecrement: vsttypes.CtrlNumber = 97;
pub const kCtrlNRPNSelectLSB: vsttypes.CtrlNumber = 98;
pub const kCtrlNRPNSelectMSB: vsttypes.CtrlNumber = 99;
pub const kCtrlRPNSelectLSB: vsttypes.CtrlNumber = 100;
pub const kCtrlRPNSelectMSB: vsttypes.CtrlNumber = 101;
pub const kCtrlAllSoundsOff: vsttypes.CtrlNumber = 120;
pub const kCtrlResetAllCtrlers: vsttypes.CtrlNumber = 121;
pub const kCtrlLocalCtrlOnOff: vsttypes.CtrlNumber = 122;
pub const kCtrlAllNotesOff: vsttypes.CtrlNumber = 123;
pub const kCtrlOmniModeOff: vsttypes.CtrlNumber = 124;
pub const kCtrlOmniModeOn: vsttypes.CtrlNumber = 125;
pub const kCtrlPolyModeOnOff: vsttypes.CtrlNumber = 126;
pub const kCtrlPolyModeOn: vsttypes.CtrlNumber = 127;
pub const kAfterTouch: vsttypes.CtrlNumber = 128;
pub const kPitchBend: vsttypes.CtrlNumber = 129;
pub const kCountCtrlNumber: vsttypes.CtrlNumber = 130;
pub const kCtrlProgramChange: vsttypes.CtrlNumber = 130;
pub const kCtrlPolyPressure: vsttypes.CtrlNumber = 131;
pub const kCtrlQuarterFrame: vsttypes.CtrlNumber = 132;
pub const kSystemSongSelect: vsttypes.CtrlNumber = 133;
pub const kSystemSongPointer: vsttypes.CtrlNumber = 134;
pub const kSystemCableSelect: vsttypes.CtrlNumber = 135;
pub const kSystemTuneRequest: vsttypes.CtrlNumber = 136;
pub const kSystemMidiClockStart: vsttypes.CtrlNumber = 137;
pub const kSystemMidiClockContinue: vsttypes.CtrlNumber = 138;
pub const kSystemMidiClockStop: vsttypes.CtrlNumber = 139;
pub const kSystemActiveSensing: vsttypes.CtrlNumber = 140;

test "MIDI controller constants match SDK values" {
    try @import("std").testing.expectEqual(@as(vsttypes.CtrlNumber, 0), kCtrlBankSelectMSB);
    try @import("std").testing.expectEqual(@as(vsttypes.CtrlNumber, 129), kPitchBend);
    try @import("std").testing.expectEqual(@as(vsttypes.CtrlNumber, 130), kCountCtrlNumber);
    try @import("std").testing.expectEqual(@as(vsttypes.CtrlNumber, 130), kCtrlProgramChange);
    try @import("std").testing.expectEqual(@as(vsttypes.CtrlNumber, 140), kSystemActiveSensing);
}
