#include "pluginterfaces/vst/vstspeaker.h"
#include <cstring>
#include "public.sdk/source/vst/vstspeakerarray.h"

#include <cstdio>

int main ()
{
	std::printf ("kSpeakerL %llu\n", static_cast<unsigned long long> (Steinberg::Vst::kSpeakerL));
	std::printf ("kSpeakerR %llu\n", static_cast<unsigned long long> (Steinberg::Vst::kSpeakerR));
	std::printf ("kSpeakerLfe %llu\n", static_cast<unsigned long long> (Steinberg::Vst::kSpeakerLfe));
	std::printf ("kSpeakerTfl %llu\n", static_cast<unsigned long long> (Steinberg::Vst::kSpeakerTfl));
	std::printf ("kSpeakerBfl %llu\n", static_cast<unsigned long long> (Steinberg::Vst::kSpeakerBfl));
	std::printf ("kSpeakerACN24 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::kSpeakerACN24));
	std::printf ("kSpeakerRw %llu\n", static_cast<unsigned long long> (Steinberg::Vst::kSpeakerRw));
	std::printf ("kStereo %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::kStereo));
	std::printf ("kStereoWide %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::kStereoWide));
	std::printf ("kStereoBF %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::kStereoBF));
	std::printf ("kCineFront %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::kCineFront));
	std::printf ("k31Music %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k31Music));
	std::printf ("k41Cine %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k41Cine));
	std::printf ("k51 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k51));
	std::printf ("k61Music %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k61Music));
	std::printf ("k71Cine %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k71Cine));
	std::printf ("k71Music %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k71Music));
	std::printf ("k71CineFullRear %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k71CineFullRear));
	std::printf ("k71Proximity %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k71Proximity));
	std::printf ("k81Cine %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k81Cine));
	std::printf ("k81Music %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k81Music));
	std::printf ("k91Cine %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k91Cine));
	std::printf ("k101Cine %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k101Cine));
	std::printf ("kAmbi1stOrderACN %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::kAmbi1stOrderACN));
	std::printf ("kAmbi7thOrderACN %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::kAmbi7thOrderACN));
	std::printf ("k40_4 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k40_4));
	std::printf ("k71CineTopCenter %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k71CineTopCenter));
	std::printf ("k51_2 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k51_2));
	std::printf ("k51_2_TS %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k51_2_TS));
	std::printf ("k41_4_1 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k41_4_1));
	std::printf ("k50_4 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k50_4));
	std::printf ("k51_4_1 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k51_4_1));
	std::printf ("k91Atmos %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k91Atmos));
	std::printf ("k72_3 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k72_3));
	std::printf ("k71_4 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k71_4));
	std::printf ("k111MPEG3D %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k111MPEG3D));
	std::printf ("k71_6 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k71_6));
	std::printf ("k91_4 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k91_4));
	std::printf ("k91_6_W %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k91_6_W));
	std::printf ("k101MPEG3D %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k101MPEG3D));
	std::printf ("k52_5 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k52_5));
	std::printf ("k51_6 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k51_6));
	std::printf ("k72_5 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k72_5));
	std::printf ("k131 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k131));
	std::printf ("k60_4_4 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k60_4_4));
	std::printf ("k100_9_3 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k100_9_3));
	std::printf ("k102_9_3 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k102_9_3));
	std::printf ("k51_5_3 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k51_5_3));
	std::printf ("k50_2_2 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k50_2_2));
	std::printf ("k70_4_2 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k70_4_2));
	std::printf ("k50_5_Sony %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k50_5_Sony));
	std::printf ("k40_2_2 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k40_2_2));
	std::printf ("k40_4_2 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k40_4_2));
	std::printf ("k50_3_2 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k50_3_2));
	std::printf ("k30_5_2 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k30_5_2));
	std::printf ("k50_4_4 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::k50_4_4));
	std::printf ("kStringStereo %s\n", Steinberg::Vst::SpeakerArr::kStringStereo);
	std::printf ("kStringStereoBF %s\n", Steinberg::Vst::SpeakerArr::kStringStereoBF);
	std::printf ("kStringCineFront %s\n", Steinberg::Vst::SpeakerArr::kStringCineFront);
	std::printf ("kString31Music %s\n", Steinberg::Vst::SpeakerArr::kString31Music);
	std::printf ("kString71CineOld %s\n", Steinberg::Vst::SpeakerArr::kString71CineOld);
	std::printf ("kString71CineFullRear %s\n", Steinberg::Vst::SpeakerArr::kString71CineFullRear);
	std::printf ("kString50_2TopSide %s\n", Steinberg::Vst::SpeakerArr::kString50_2TopSide);
	std::printf ("kString101Cine %s\n", Steinberg::Vst::SpeakerArr::kString101Cine);
	std::printf ("kString72_5 %s\n", Steinberg::Vst::SpeakerArr::kString72_5);
	std::printf ("kString91_6_W %s\n", Steinberg::Vst::SpeakerArr::kString91_6_W);
	std::printf ("kString50_5 %s\n", Steinberg::Vst::SpeakerArr::kString50_5);
	std::printf ("kString131 %s\n", Steinberg::Vst::SpeakerArr::kString131);
	std::printf ("kString222 %s\n", Steinberg::Vst::SpeakerArr::kString222);
	std::printf ("kString50_5_Sony %s\n", Steinberg::Vst::SpeakerArr::kString50_5_Sony);
	std::printf ("kString40_2_2 %s\n", Steinberg::Vst::SpeakerArr::kString40_2_2);
	std::printf ("kString50_4_4 %s\n", Steinberg::Vst::SpeakerArr::kString50_4_4);
	std::printf ("kStringAmbi7thOrder %s\n", Steinberg::Vst::SpeakerArr::kStringAmbi7thOrder);
	std::printf ("kStringStereoS %s\n", Steinberg::Vst::SpeakerArr::kStringStereoS);
	std::printf ("kStringStereoBFS %s\n", Steinberg::Vst::SpeakerArr::kStringStereoBFS);
	std::printf ("kStringCineFrontS %s\n", Steinberg::Vst::SpeakerArr::kStringCineFrontS);
	std::printf ("kString31MusicS %s\n", Steinberg::Vst::SpeakerArr::kString31MusicS);
	std::printf ("kString71CineFullRearS %s\n", Steinberg::Vst::SpeakerArr::kString71CineFullRearS);
	std::printf ("kString51_2TopSideS %s\n", Steinberg::Vst::SpeakerArr::kString51_2TopSideS);
	std::printf ("kString101CineS %s\n", Steinberg::Vst::SpeakerArr::kString101CineS);
	std::printf ("kString72_3S %s\n", Steinberg::Vst::SpeakerArr::kString72_3S);
	std::printf ("kString91_6_WS %s\n", Steinberg::Vst::SpeakerArr::kString91_6_WS);
	std::printf ("kString51_5S %s\n", Steinberg::Vst::SpeakerArr::kString51_5S);
	std::printf ("kString72_5S %s\n", Steinberg::Vst::SpeakerArr::kString72_5S);
	std::printf ("kString40_2_2S %s\n", Steinberg::Vst::SpeakerArr::kString40_2_2S);
	std::printf ("kString222S %s\n", Steinberg::Vst::SpeakerArr::kString222S);
	std::printf ("kStringAmbi7thOrderS %s\n", Steinberg::Vst::SpeakerArr::kStringAmbi7thOrderS);
	std::printf ("getChannelCount.k51 %d\n", Steinberg::Vst::SpeakerArr::getChannelCount (Steinberg::Vst::SpeakerArr::k51));
	std::printf ("getSpeakerIndex.R.stereo %d\n", Steinberg::Vst::SpeakerArr::getSpeakerIndex (Steinberg::Vst::kSpeakerR, Steinberg::Vst::SpeakerArr::kStereo));
	std::printf ("getSpeaker.k51.2 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::getSpeaker (Steinberg::Vst::SpeakerArr::k51, 2)));
	std::printf ("isSubsetOf.stereo.51 %d\n", Steinberg::Vst::SpeakerArr::isSubsetOf (Steinberg::Vst::SpeakerArr::kStereo, Steinberg::Vst::SpeakerArr::k51));
	std::printf ("isAuro.51_5 %d\n", Steinberg::Vst::SpeakerArr::isAuro (Steinberg::Vst::SpeakerArr::k51_5));
	std::printf ("isAuro.51 %d\n", Steinberg::Vst::SpeakerArr::isAuro (Steinberg::Vst::SpeakerArr::k51));
	std::printf ("hasTopSpeakers.50_4 %d\n", Steinberg::Vst::SpeakerArr::hasTopSpeakers (Steinberg::Vst::SpeakerArr::k50_4));
	std::printf ("hasBottomSpeakers.50_4 %d\n", Steinberg::Vst::SpeakerArr::hasBottomSpeakers (Steinberg::Vst::SpeakerArr::k50_4));
	std::printf ("hasMiddleSpeakers.50_4 %d\n", Steinberg::Vst::SpeakerArr::hasMiddleSpeakers (Steinberg::Vst::SpeakerArr::k50_4));
	std::printf ("hasLfe.51 %d\n", Steinberg::Vst::SpeakerArr::hasLfe (Steinberg::Vst::SpeakerArr::k51));
	std::printf ("is3D.50_4 %d\n", Steinberg::Vst::SpeakerArr::is3D (Steinberg::Vst::SpeakerArr::k50_4));
	std::printf ("isAmbisonics.ambi1 %d\n", Steinberg::Vst::SpeakerArr::isAmbisonics (Steinberg::Vst::SpeakerArr::kAmbi1stOrderACN));
	std::printf ("convertAmbi1234.ACN4 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::convertSpeaker_Ambi_1234Order_to_Ambi567Order (Steinberg::Vst::kSpeakerACN4)));
	std::printf ("convertAmbi567.ACN4 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::convertSpeaker_Ambi_567Order_to_Ambi1234Order (Steinberg::Vst::kSpeakerACN4)));
	std::printf ("convertAmbi567.L %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::convertSpeaker_Ambi_567Order_to_Ambi1234Order (Steinberg::Vst::kSpeakerL)));
	std::printf ("getArrangementFromString.71CineOld %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::getSpeakerArrangementFromString (Steinberg::Vst::SpeakerArr::kString71CineOld)));
	std::printf ("getArrangementFromString.51_2TopSide %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::getSpeakerArrangementFromString (Steinberg::Vst::SpeakerArr::kString51_2TopSide)));
	std::printf ("getArrangementFromString.Ambi7 %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::getSpeakerArrangementFromString (Steinberg::Vst::SpeakerArr::kStringAmbi7thOrder)));
	std::printf ("getArrangementFromString.unknown %llu\n", static_cast<unsigned long long> (Steinberg::Vst::SpeakerArr::getSpeakerArrangementFromString ("unknown")));
	std::printf ("getArrangementString.51 %s\n", Steinberg::Vst::SpeakerArr::getSpeakerArrangementString (Steinberg::Vst::SpeakerArr::k51, false));
	std::printf ("getArrangementString.51.named %s\n", Steinberg::Vst::SpeakerArr::getSpeakerArrangementString (Steinberg::Vst::SpeakerArr::k51, true));
	std::printf ("getArrangementString.51_2_TS %s\n", Steinberg::Vst::SpeakerArr::getSpeakerArrangementString (Steinberg::Vst::SpeakerArr::k51_2_TS, false));
	std::printf ("getArrangementString.222.named %s\n", Steinberg::Vst::SpeakerArr::getSpeakerArrangementString (Steinberg::Vst::SpeakerArr::k222, true));
	std::printf ("getArrangementString.ambi7 %s\n", Steinberg::Vst::SpeakerArr::getSpeakerArrangementString (Steinberg::Vst::SpeakerArr::kAmbi7thOrderACN, false));
	std::printf ("getArrangementString.unknown %s\n", Steinberg::Vst::SpeakerArr::getSpeakerArrangementString (static_cast<Steinberg::Vst::SpeakerArrangement> (0x4000000000000000ULL), false));
	std::printf ("getSpeakerShortName.51.3 %s\n", Steinberg::Vst::SpeakerArr::getSpeakerShortName (Steinberg::Vst::SpeakerArr::k51, 3));
	std::printf ("getSpeakerShortName.ambi1.2 %s\n", Steinberg::Vst::SpeakerArr::getSpeakerShortName (Steinberg::Vst::SpeakerArr::kAmbi1stOrderACN, 2));
	std::printf ("getSpeakerShortName.50_4_4.10 %s\n", Steinberg::Vst::SpeakerArr::getSpeakerShortName (Steinberg::Vst::SpeakerArr::k50_4_4, 10));
	std::printf ("getSpeakerShortName.51.99 %s\n", Steinberg::Vst::SpeakerArr::getSpeakerShortName (Steinberg::Vst::SpeakerArr::k51, 99));
	Steinberg::Vst::SpeakerArray speakerArray (Steinberg::Vst::SpeakerArr::k51);
	std::printf ("SpeakerArray.total.51 %d\n", speakerArray.total ());
	std::printf ("SpeakerArray.at.51.0 %llu\n", static_cast<unsigned long long> (speakerArray.at (0)));
	std::printf ("SpeakerArray.at.51.3 %llu\n", static_cast<unsigned long long> (speakerArray.at (3)));
	std::printf ("SpeakerArray.getArrangement.51 %llu\n", static_cast<unsigned long long> (speakerArray.getArrangement ()));
	std::printf ("SpeakerArray.getSpeakerIndex.Lfe %d\n", speakerArray.getSpeakerIndex (Steinberg::Vst::kSpeakerLfe));
	speakerArray.setArrangement (Steinberg::Vst::SpeakerArr::k50_4);
	std::printf ("SpeakerArray.total.50_4 %d\n", speakerArray.total ());
	std::printf ("SpeakerArray.getArrangement.50_4 %llu\n", static_cast<unsigned long long> (speakerArray.getArrangement ()));
	return 0;
}
