const std = @import("std");
const speaker = @import("vst3-zig").pluginterfaces.vst.vstspeaker;

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    try stdout.print("kSpeakerL {}\n", .{speaker.kSpeakerL});
    try stdout.print("kSpeakerR {}\n", .{speaker.kSpeakerR});
    try stdout.print("kSpeakerLfe {}\n", .{speaker.kSpeakerLfe});
    try stdout.print("kSpeakerTfl {}\n", .{speaker.kSpeakerTfl});
    try stdout.print("kSpeakerBfl {}\n", .{speaker.kSpeakerBfl});
    try stdout.print("kSpeakerACN24 {}\n", .{speaker.kSpeakerACN24});
    try stdout.print("kSpeakerRw {}\n", .{speaker.kSpeakerRw});
    try stdout.print("kStereo {}\n", .{speaker.SpeakerArr.kStereo});
    try stdout.print("kStereoWide {}\n", .{speaker.SpeakerArr.kStereoWide});
    try stdout.print("kStereoBF {}\n", .{speaker.SpeakerArr.kStereoBF});
    try stdout.print("kCineFront {}\n", .{speaker.SpeakerArr.kCineFront});
    try stdout.print("k31Music {}\n", .{speaker.SpeakerArr.k31Music});
    try stdout.print("k41Cine {}\n", .{speaker.SpeakerArr.k41Cine});
    try stdout.print("k51 {}\n", .{speaker.SpeakerArr.k51});
    try stdout.print("k61Music {}\n", .{speaker.SpeakerArr.k61Music});
    try stdout.print("k71Cine {}\n", .{speaker.SpeakerArr.k71Cine});
    try stdout.print("k71Music {}\n", .{speaker.SpeakerArr.k71Music});
    try stdout.print("k71CineFullRear {}\n", .{speaker.SpeakerArr.k71CineFullRear});
    try stdout.print("k71Proximity {}\n", .{speaker.SpeakerArr.k71Proximity});
    try stdout.print("k81Cine {}\n", .{speaker.SpeakerArr.k81Cine});
    try stdout.print("k81Music {}\n", .{speaker.SpeakerArr.k81Music});
    try stdout.print("k91Cine {}\n", .{speaker.SpeakerArr.k91Cine});
    try stdout.print("k101Cine {}\n", .{speaker.SpeakerArr.k101Cine});
    try stdout.print("kAmbi1stOrderACN {}\n", .{speaker.SpeakerArr.kAmbi1stOrderACN});
    try stdout.print("kAmbi7thOrderACN {}\n", .{speaker.SpeakerArr.kAmbi7thOrderACN});
    try stdout.print("k40_4 {}\n", .{speaker.SpeakerArr.k40_4});
    try stdout.print("k71CineTopCenter {}\n", .{speaker.SpeakerArr.k71CineTopCenter});
    try stdout.print("k51_2 {}\n", .{speaker.SpeakerArr.k51_2});
    try stdout.print("k51_2_TS {}\n", .{speaker.SpeakerArr.k51_2_TS});
    try stdout.print("k41_4_1 {}\n", .{speaker.SpeakerArr.k41_4_1});
    try stdout.print("k50_4 {}\n", .{speaker.SpeakerArr.k50_4});
    try stdout.print("k51_4_1 {}\n", .{speaker.SpeakerArr.k51_4_1});
    try stdout.print("k91Atmos {}\n", .{speaker.SpeakerArr.k91Atmos});
    try stdout.print("k72_3 {}\n", .{speaker.SpeakerArr.k72_3});
    try stdout.print("k71_4 {}\n", .{speaker.SpeakerArr.k71_4});
    try stdout.print("k111MPEG3D {}\n", .{speaker.SpeakerArr.k111MPEG3D});
    try stdout.print("k71_6 {}\n", .{speaker.SpeakerArr.k71_6});
    try stdout.print("k91_4 {}\n", .{speaker.SpeakerArr.k91_4});
    try stdout.print("k91_6_W {}\n", .{speaker.SpeakerArr.k91_6_W});
    try stdout.print("k101MPEG3D {}\n", .{speaker.SpeakerArr.k101MPEG3D});
    try stdout.print("k52_5 {}\n", .{speaker.SpeakerArr.k52_5});
    try stdout.print("k51_6 {}\n", .{speaker.SpeakerArr.k51_6});
    try stdout.print("k72_5 {}\n", .{speaker.SpeakerArr.k72_5});
    try stdout.print("k131 {}\n", .{speaker.SpeakerArr.k131});
    try stdout.print("k60_4_4 {}\n", .{speaker.SpeakerArr.k60_4_4});
    try stdout.print("k100_9_3 {}\n", .{speaker.SpeakerArr.k100_9_3});
    try stdout.print("k102_9_3 {}\n", .{speaker.SpeakerArr.k102_9_3});
    try stdout.print("k51_5_3 {}\n", .{speaker.SpeakerArr.k51_5_3});
    try stdout.print("k50_2_2 {}\n", .{speaker.SpeakerArr.k50_2_2});
    try stdout.print("k70_4_2 {}\n", .{speaker.SpeakerArr.k70_4_2});
    try stdout.print("k50_5_Sony {}\n", .{speaker.SpeakerArr.k50_5_Sony});
    try stdout.print("k40_2_2 {}\n", .{speaker.SpeakerArr.k40_2_2});
    try stdout.print("k40_4_2 {}\n", .{speaker.SpeakerArr.k40_4_2});
    try stdout.print("k50_3_2 {}\n", .{speaker.SpeakerArr.k50_3_2});
    try stdout.print("k30_5_2 {}\n", .{speaker.SpeakerArr.k30_5_2});
    try stdout.print("k50_4_4 {}\n", .{speaker.SpeakerArr.k50_4_4});
    try stdout.print("kStringStereo {s}\n", .{speaker.SpeakerArrStrings.kStringStereo});
    try stdout.print("kStringStereoBF {s}\n", .{speaker.SpeakerArrStrings.kStringStereoBF});
    try stdout.print("kStringCineFront {s}\n", .{speaker.SpeakerArrStrings.kStringCineFront});
    try stdout.print("kString31Music {s}\n", .{speaker.SpeakerArrStrings.kString31Music});
    try stdout.print("kString71CineOld {s}\n", .{speaker.SpeakerArrStrings.kString71CineOld});
    try stdout.print("kString71CineFullRear {s}\n", .{speaker.SpeakerArrStrings.kString71CineFullRear});
    try stdout.print("kString50_2TopSide {s}\n", .{speaker.SpeakerArrStrings.kString50_2TopSide});
    try stdout.print("kString101Cine {s}\n", .{speaker.SpeakerArrStrings.kString101Cine});
    try stdout.print("kString72_5 {s}\n", .{speaker.SpeakerArrStrings.kString72_5});
    try stdout.print("kString91_6_W {s}\n", .{speaker.SpeakerArrStrings.kString91_6_W});
    try stdout.print("kString50_5 {s}\n", .{speaker.SpeakerArrStrings.kString50_5});
    try stdout.print("kString131 {s}\n", .{speaker.SpeakerArrStrings.kString131});
    try stdout.print("kString222 {s}\n", .{speaker.SpeakerArrStrings.kString222});
    try stdout.print("kString50_5_Sony {s}\n", .{speaker.SpeakerArrStrings.kString50_5_Sony});
    try stdout.print("kString40_2_2 {s}\n", .{speaker.SpeakerArrStrings.kString40_2_2});
    try stdout.print("kString50_4_4 {s}\n", .{speaker.SpeakerArrStrings.kString50_4_4});
    try stdout.print("kStringAmbi7thOrder {s}\n", .{speaker.SpeakerArrStrings.kStringAmbi7thOrder});
    try stdout.print("kStringStereoS {s}\n", .{speaker.SpeakerArrStrings.kStringStereoS});
    try stdout.print("kStringStereoBFS {s}\n", .{speaker.SpeakerArrStrings.kStringStereoBFS});
    try stdout.print("kStringCineFrontS {s}\n", .{speaker.SpeakerArrStrings.kStringCineFrontS});
    try stdout.print("kString31MusicS {s}\n", .{speaker.SpeakerArrStrings.kString31MusicS});
    try stdout.print("kString71CineFullRearS {s}\n", .{speaker.SpeakerArrStrings.kString71CineFullRearS});
    try stdout.print("kString51_2TopSideS {s}\n", .{speaker.SpeakerArrStrings.kString51_2TopSideS});
    try stdout.print("kString101CineS {s}\n", .{speaker.SpeakerArrStrings.kString101CineS});
    try stdout.print("kString72_3S {s}\n", .{speaker.SpeakerArrStrings.kString72_3S});
    try stdout.print("kString91_6_WS {s}\n", .{speaker.SpeakerArrStrings.kString91_6_WS});
    try stdout.print("kString51_5S {s}\n", .{speaker.SpeakerArrStrings.kString51_5S});
    try stdout.print("kString72_5S {s}\n", .{speaker.SpeakerArrStrings.kString72_5S});
    try stdout.print("kString40_2_2S {s}\n", .{speaker.SpeakerArrStrings.kString40_2_2S});
    try stdout.print("kString222S {s}\n", .{speaker.SpeakerArrStrings.kString222S});
    try stdout.print("kStringAmbi7thOrderS {s}\n", .{speaker.SpeakerArrStrings.kStringAmbi7thOrderS});
    try stdout.print("getChannelCount.k51 {}\n", .{speaker.getChannelCount(speaker.SpeakerArr.k51)});
    try stdout.print("getSpeakerIndex.R.stereo {}\n", .{speaker.getSpeakerIndex(speaker.kSpeakerR, speaker.SpeakerArr.kStereo)});
    try stdout.print("getSpeaker.k51.2 {}\n", .{speaker.getSpeaker(speaker.SpeakerArr.k51, 2)});
    try stdout.print("isSubsetOf.stereo.51 {}\n", .{@intFromBool(speaker.isSubsetOf(speaker.SpeakerArr.kStereo, speaker.SpeakerArr.k51))});
    try stdout.print("isAuro.51_5 {}\n", .{@intFromBool(speaker.isAuro(speaker.SpeakerArr.k51_5))});
    try stdout.print("isAuro.51 {}\n", .{@intFromBool(speaker.isAuro(speaker.SpeakerArr.k51))});
    try stdout.print("hasTopSpeakers.50_4 {}\n", .{@intFromBool(speaker.hasTopSpeakers(speaker.SpeakerArr.k50_4))});
    try stdout.print("hasBottomSpeakers.50_4 {}\n", .{@intFromBool(speaker.hasBottomSpeakers(speaker.SpeakerArr.k50_4))});
    try stdout.print("hasMiddleSpeakers.50_4 {}\n", .{@intFromBool(speaker.hasMiddleSpeakers(speaker.SpeakerArr.k50_4))});
    try stdout.print("hasLfe.51 {}\n", .{@intFromBool(speaker.hasLfe(speaker.SpeakerArr.k51))});
    try stdout.print("is3D.50_4 {}\n", .{@intFromBool(speaker.is3D(speaker.SpeakerArr.k50_4))});
    try stdout.print("isAmbisonics.ambi1 {}\n", .{@intFromBool(speaker.isAmbisonics(speaker.SpeakerArr.kAmbi1stOrderACN))});
    try stdout.print("convertAmbi1234.ACN4 {}\n", .{speaker.convertSpeakerAmbi1234OrderToAmbi567Order(speaker.kSpeakerACN4)});
    try stdout.print("convertAmbi567.ACN4 {}\n", .{speaker.convertSpeakerAmbi567OrderToAmbi1234Order(speaker.kSpeakerACN4)});
    try stdout.print("convertAmbi567.L {}\n", .{speaker.convertSpeakerAmbi567OrderToAmbi1234Order(speaker.kSpeakerL)});
    try stdout.print("getArrangementFromString.71CineOld {}\n", .{speaker.getSpeakerArrangementFromString(speaker.SpeakerArrStrings.kString71CineOld)});
    try stdout.print("getArrangementFromString.51_2TopSide {}\n", .{speaker.getSpeakerArrangementFromString(speaker.SpeakerArrStrings.kString51_2TopSide)});
    try stdout.print("getArrangementFromString.Ambi7 {}\n", .{speaker.getSpeakerArrangementFromString(speaker.SpeakerArrStrings.kStringAmbi7thOrder)});
    try stdout.print("getArrangementFromString.unknown {}\n", .{speaker.getSpeakerArrangementFromString("unknown")});
    try stdout.print("getArrangementString.51 {s}\n", .{speaker.getSpeakerArrangementString(speaker.SpeakerArr.k51, false)});
    try stdout.print("getArrangementString.51.named {s}\n", .{speaker.getSpeakerArrangementString(speaker.SpeakerArr.k51, true)});
    try stdout.print("getArrangementString.51_2_TS {s}\n", .{speaker.getSpeakerArrangementString(speaker.SpeakerArr.k51_2_TS, false)});
    try stdout.print("getArrangementString.222.named {s}\n", .{speaker.getSpeakerArrangementString(speaker.SpeakerArr.k222, true)});
    try stdout.print("getArrangementString.ambi7 {s}\n", .{speaker.getSpeakerArrangementString(speaker.SpeakerArr.kAmbi7thOrderACN, false)});
    try stdout.print("getArrangementString.unknown {s}\n", .{speaker.getSpeakerArrangementString(0x4000000000000000, false)});
    var speaker_array = speaker.SpeakerArray.init(speaker.SpeakerArr.k51);
    try stdout.print("SpeakerArray.total.51 {}\n", .{speaker_array.total()});
    try stdout.print("SpeakerArray.at.51.0 {}\n", .{speaker_array.at(0)});
    try stdout.print("SpeakerArray.at.51.3 {}\n", .{speaker_array.at(3)});
    try stdout.print("SpeakerArray.getArrangement.51 {}\n", .{speaker_array.getArrangement()});
    try stdout.print("SpeakerArray.getSpeakerIndex.Lfe {}\n", .{speaker_array.getSpeakerIndex(speaker.kSpeakerLfe)});
    speaker_array.setArrangement(speaker.SpeakerArr.k50_4);
    try stdout.print("SpeakerArray.total.50_4 {}\n", .{speaker_array.total()});
    try stdout.print("SpeakerArray.getArrangement.50_4 {}\n", .{speaker_array.getArrangement()});
}
