const std = @import("std");
const core = @import("adm_xml/core.zig");

pub const max_adm_positions = core.max_adm_positions;
pub const max_adm_speaker_labels = core.max_adm_speaker_labels;
pub const max_adm_speaker_label_bytes = core.max_adm_speaker_label_bytes;
pub const max_adm_matrix_coefficients = core.max_adm_matrix_coefficients;
pub const max_adm_exclusion_zones = core.max_adm_exclusion_zones;
pub const Limits = core.Limits;
pub const default_limits = core.default_limits;
pub const Declaration = core.Declaration;
pub const ReferenceKind = core.ReferenceKind;
pub const Reference = core.Reference;
pub const Profile = core.Profile;
pub const EmissionProfileLevel = core.EmissionProfileLevel;
pub const EmissionPcmEssence = core.EmissionPcmEssence;
pub const EmissionSerialFlowState = core.EmissionSerialFlowState;
pub const Tag = core.Tag;
pub const TagTarget = core.TagTarget;
pub const TagItem = core.TagItem;
pub const GainUnit = core.GainUnit;
pub const Gain = core.Gain;
pub const Frequency = core.Frequency;
pub const JumpPosition = core.JumpPosition;
pub const HeadphoneVirtualise = core.HeadphoneVirtualise;
pub const Coordinate = core.Coordinate;
pub const PositionBound = core.PositionBound;
pub const ScreenEdge = core.ScreenEdge;
pub const Position = core.Position;
pub const SpeakerLabel = core.SpeakerLabel;
pub const ObjectDivergence = core.ObjectDivergence;
pub const ChannelLock = core.ChannelLock;
pub const CartesianExclusionZone = core.CartesianExclusionZone;
pub const PolarExclusionZone = core.PolarExclusionZone;
pub const ExclusionZone = core.ExclusionZone;
pub const HoaNormalization = core.HoaNormalization;
pub const AdmText = core.AdmText;
pub const MatrixCoefficient = core.MatrixCoefficient;
pub const BlockFormat = core.BlockFormat;
pub const Extension = core.Extension;
pub const UntypedElement = core.UntypedElement;
pub const ExtensionIterator = core.ExtensionIterator;
pub const UntypedElementIterator = core.UntypedElementIterator;
pub const ExtensionAttribute = core.ExtensionAttribute;
pub const ExtensionAttributeIterator = core.ExtensionAttributeIterator;
pub const UntypedAttribute = core.UntypedAttribute;
pub const UntypedAttributeIterator = core.UntypedAttributeIterator;
pub const Document = core.Document;
pub const ProfileIterator = core.ProfileIterator;
pub const TagIterator = core.TagIterator;
pub const BlockIterator = core.BlockIterator;
pub const DeclarationIterator = core.DeclarationIterator;
pub const ReferenceIterator = core.ReferenceIterator;

test "ADM XML facade preserves exact public identities" {
    try std.testing.expect(Limits == core.Limits);
    try std.testing.expect(Document == core.Document);
    try std.testing.expect(BlockFormat == core.BlockFormat);
    try std.testing.expect(DeclarationIterator == core.DeclarationIterator);
    try std.testing.expect(ReferenceIterator == core.ReferenceIterator);
    try std.testing.expect(ProfileIterator == core.ProfileIterator);
    try std.testing.expect(TagIterator == core.TagIterator);
    try std.testing.expect(BlockIterator == core.BlockIterator);
    try std.testing.expect(ExtensionIterator == core.ExtensionIterator);
    try std.testing.expect(UntypedElementIterator == core.UntypedElementIterator);
}
